#price
PEPPERONI_PIZZA = 28500
HAWAIAN_PIZZA = 31000
POTATO_PIZZA = 26000

CHEESE_TOPPING = 500
OLIVE_TOPPING = 600
PEPPERONI_TOPPING = 400
PINEAPPLE_TOPPING = 600
ONION_TOPPING = 300

ORIGINAL_EDGE = 0
THIN_EDGE = 1000
CHEESE_EDGE = 2000

MEDIUM_SIZE = 0
LARGE_SIZE = 5000

#type
PIZZA_TYPE = {
    0 : PEPPERONI_PIZZA,
    1 : HAWAIAN_PIZZA,
    2 : POTATO_PIZZA
}
TOPPING_TYPE = {
    0 : CHEESE_TOPPING,
    1 : OLIVE_TOPPING,
    2 : PEPPERONI_TOPPING,
    3 : PINEAPPLE_TOPPING,
    4 : ONION_TOPPING
}
DOUGH_EDGE = {
    0 : ORIGINAL_EDGE,
    1 : THIN_EDGE,
    2 : CHEESE_EDGE
}
PIZZA_SIZE = {
    0 : MEDIUM_SIZE,
    1 : LARGE_SIZE
}